name: unitrack_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8

  # ✅ ONLY HERE (dependency)
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# ✅ THIS IS CONFIG (OUTSIDE dependencies)
flutter_native_splash:
  color: "#080D19"
  image: assets/logo/logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo.png
